Throttling:
  limit: 1000
  timeSpan: 1
  timeUnit: MINUTES
timeoutUnit: SECONDS
ssl:
  port: 443
  keyStorePassword: password
  enable: false
  keyStore: keyStore
timeout: 15
buffer:
  in: 100000
  out: 100000
mongodb:
  dbMorphia: metrics
  collectionSessions: sessions
  dbSessions: metrics
  uri: mongodb://localhost:27017
  enabled: true
limits:
  limitPostBasicSize: 8190
  limitRequestLineSize: 8190
disableViews: false
middleware:
  loginRedirect: login
enableSecurityManager: true
enableInputThread: true
cache:
  cachedFilesExpiry: 86400
  cachedAccountsMaxItems: 1000
  cachedIncludesExpiry: 3600
  cachedIncludesMaxItems: 1000
  cachedAccountIdsExpiry: 86400
  cachedAccountsExpiry: 1800
  cachedBodiesMaxItems: 1000
  cachedFilesMaxItems: 1000
  cachedAccountIdsMaxItems: 1000
  cachedSessionsMaxItems: 1000
  cachedBodiesExpiry: 3600
sessions:
  enableDb: true
  sessionTimeout: 86400
debug: true
webAddress: localhost
templates:
  engine: CRUSH
  applyTemplates:
  - ALL
logPrefix: Web
gzip: true
Pools:
  httpsBossGroupThreads: 0
  md5Handlers: 2
  gzipHandlers: 2
  httpWorkerGroupThreads: 0
  httpBossGroupThreads: 0
  httpsWorkerGroupThreads: 0
MemoryGuard:
  runEveryMillis: 600000
verbose: false
loadWebJars: true
application:
  databaseImplementation: mongo
  main: ''
port: 30000
internalAddons:
  disabled: []
logging:
  logFormat: '&0[&c${applicationPrefix}&0]&0[&c${logPrefix}&0]&0[&c${thread}&0]&0[&c${timeStamp}&0]
    &r${message}'
autoDetectViews: false
exitOnStop: true
